---

- name: "{{ timezone_task_prefix }} configure /etc/timezone"
  copy:
    dest: "/etc/timezone"
    content: |
      {{ timezone_tz }}
  when: ansible_os_family == "Debian"

- name: "{{ timezone_task_prefix }} configure /etc/sysconfig/clock"
  copy:
    dest: "/etc/sysconfig/clock"
    content: |
      ZONE="{{ timezone_tz }}"
  when: ansible_os_family == "RedHat"

- name: "{{ timezone_task_prefix }} configure /etc/localtime"
  file:
    src: "/usr/share/zoneinfo/{{ timezone_tz }}"
    dest: "/etc/localtime"
    state: link
    force: true

...
